<a href="https://colab.research.google.com/github/bobbykbose37/shivanshe_femi/blob/main/Friday%2011th.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np 
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print('First array:') 
print (a) 
print ('\n')  

print ('Second array:') 
b = np.array([10,10,10])
print (b) 
print ('\n')  

print ('Add the two arrays:') 
print (np.add(a,b)) 
print ('\n')  

print ('Subtract the two arrays:') 
print (np.subtract(a,b)) 
print ('\n')  

print ('Multiply the two arrays:') 
print (np.multiply(a,b)) 
print ('\n')  

print ('Divide the two arrays:') 
print (np.divide(a,b))

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second array:
[10 10 10]


Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


Multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [9]:
a = np.array([[3,7],[9,1]]) 

print ('Our array is:') 
print (a) 
print ('\n')

print ('Applying sort() function:') 
print (np.sort(a)) 
print ('\n') 
  
print ('Sort along axis 0:') 
print (np.sort(a, axis = 0)) 
print ('\n')  

# Order parameter in sort function 
dt = np.dtype([('name', 'S10'),('age', int)]) 
a = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype = dt)

print ('Our array is:') 
print (a) 
print ('\n')  

print ('Order by name:') 
print (np.sort(a, order = 'age'))

Our array is:
[[3 7]
 [9 1]]


Applying sort() function:
[[3 7]
 [1 9]]


Sort along axis 0:
[[3 1]
 [9 7]]


Our array is:
[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]


Order by name:
[(b'ravi', 17) (b'raju', 21) (b'anil', 25) (b'amar', 27)]


In [7]:
a = np.array([10,100,1000]) 

print('Our array is:') 
print (a) 
print ('\n')  

print ('Applying power function:') 
print (np.power(a,2)) 
print ('\n')  

print ('Second array:') 
b = np.array([1,2,3]) 
print (b) 
print ('\n')  

print ('Applying power function again:') 
print (np.power(a,b))

Our array is:
[  10  100 1000]


Applying power function:
[    100   10000 1000000]


Second array:
[1 2 3]


Applying power function again:
[        10      10000 1000000000]


In [10]:
import numpy.matlib 


In [20]:
print(np.matlib.empty((2,2)))
print(np.matlib.empty((3,3)))
print(np.matlib.empty((4,4)))
print(np.matlib.empty((6,6)))
print(np.matlib.empty((9,9)))


[[1.5e-323 3.5e-323]
 [4.4e-323 4.9e-324]]
[[9.73262897e-315 6.79960809e-318 5.88926641e-310]
 [5.30498948e-313 1.07070480e+200 2.36414097e-308]
 [7.50128708e+218 1.44667362e-319 1.33397724e-322]]
[[4.65521746e-310 1.06099790e-312 1.01855798e-312 9.54898106e-313]
 [1.03977794e-312 1.03977794e-312 1.23075756e-312 1.18831764e-312]
 [1.08221785e-312 9.76118064e-313 1.12465777e-312 1.14587773e-312]
 [1.16709769e-312 4.44659081e-322 0.00000000e+000 0.00000000e+000]]
[[4.6552167e-310 0.0000000e+000 0.0000000e+000 0.0000000e+000
  0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
  0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
  0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
  0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
  0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+0