<a href="https://colab.research.google.com/github/bobbykbose37/shivanshe_femi/blob/main/shivanshe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np 

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0],[0]] 
print(y)

[1]


In [7]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print('Our array is:') 
print(x) 
print('\n')   
print('The items greater than 5 are:') 
print(x[x > 5])

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater than 5 are:
[ 6  7  8  9 10 11]


In [17]:
a = np.arange(10) 
print(a)
b = a[2:7:2] 
print(b)
b=a[5]
print(b)
print(a[::-2])


[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
5
[9 7 5 3 1]


In [ ]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0]) 

In [18]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)

[ 10  40  90 160]


In [19]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Original array is:')
print(a)
print('\n')

print('Modified array is:')
for x in np.nditer(a):
   print(x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55
